mainpage/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django_registration.backends.activation.views import RegistrationView

from mainpage.forms import LoginTimezoneForm
from mainpage.forms import FormWithCaptcha

admin.autodiscover()

urlpatterns = [
    # Creating a sitemap.xml
    re_path(r"^sitemap\.xml", include("mainpage.sitemap_urls")),
    # Static view of robots.txt
    re_path(
        r"^robots\.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # Uncomment the next line to enable the admin:
    re_path(r"^admin/", admin.site.urls),
    # Django builtin / Registration
    # overwrite registration with own implementation
    re_path(
        r"^accounts/register/$",
        RegistrationView.as_view(form_class=FormWithCaptcha),
        name="django_registration_register",
    ),
    re_path(r"^accounts/", include("django_registration.backends.activation.urls")),
    re_path(
        r"^accounts/login/$", LoginView.as_view(authentication_form=LoginTimezoneForm)
    ),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^ratings/", include("star_ratings.urls", namespace="ratings")),
    # Formerly 3rd party
    re_path(r"^notification/", include("notification.urls")),
    re_path(r"^messages/", include("django_messages_wl.urls")),
    re_path(r"^threadedcomments/", include("threadedcomments.urls")),
    # Redirect old urls to new documentation
    re_path(
        r"^docs/wl/(?P<path>.*)",
        RedirectView.as_view(url="/documentation/%(path)s", permanent=True),
        name="docs_wl",
    ),
    re_path(
        r"^docs/$",
        RedirectView.as_view(url="/documentation/index.html", permanent=True),
        name="docs",
    ),
    # 3rd party, modified for widelands
    re_path(r"^wiki/", include("wiki.urls")),
    re_path(r"^news/", include("news.urls")),
    re_path(r"^forum/", include("pybb.urls")),
    # WL specific:
    re_path(r"^", include("mainpage.mainpage_urls")),
    re_path(
        r"^help/(?P<path>.*)",
        RedirectView.as_view(url="/encyclopedia/%(path)s", permanent=True),
    ),  # to not break old links
    re_path(r"^encyclopedia/", include("wlhelp.urls")),
    re_path(r"^webchat/", include("wlwebchat.urls")),
    re_path(r"^images/", include("wlimages.urls")),
    re_path(r"^profile/", include("wlprofile.urls")),
    re_path(r"^search/", include("wlsearch.urls")),
    re_path(r"^poll/", include("wlpoll.urls")),
    re_path(r"^maps/", include("wlmaps.urls")),
    re_path(r"^screenshots/", include("wlscreens.urls")),
    re_path(r"^ggz/", include("wlggz.urls")),
    re_path(r"^moderated/", include("check_input.urls")),
    re_path(r"^scheduling/", include("wlscheduling.urls")),
    re_path(r"^privacy/", include("privacy_policy.urls")),
    re_path(r"^addons/", include("wladdons_settings.urls")),
    # See: https://github.com/widelands/widelands-website/issues/376
    re_path(
        r"^feeds/news/",
        RedirectView.as_view(url="/news/feed", permanent=True),
    ),
]

try:
    from .local_urls import local_urlpatterns

    urlpatterns += local_urlpatterns
except ImportError:
    pass

handler500 = "mainpage.views.custom_http_500"

news/urls.py
from django.urls import re_path
from news.views import NewsList, YearNews, MonthNews, NewsDetail, CategoryView
from news.feeds import NewsPostsFeed


urlpatterns = [
    re_path(
        r"^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>[-\w]+)/$",
        NewsDetail.as_view(),
        name="news_detail",
    ),
    re_path(
        r"^(?P<year>\d{4})/(?P<month>[-\w]+)/$",
        MonthNews.as_view(),
        name="news_archive_month",
    ),
    re_path(r"^(?P<year>\d{4})/$", YearNews.as_view(), name="news_archive_year"),
    re_path(
        r"^category/(?P<slug>[-\w]+)/", CategoryView.as_view(), name="category_posts"
    ),
    re_path(
        r"^$", NewsList.as_view(template_name="news/post_list.html"), name="news_index"
    ),
    # Feed
    re_path(r"^feed/$", NewsPostsFeed()),
]

pybb/urls.py
from django.urls import re_path

from pybb import views
from pybb.feeds import LastPosts, LastTopics

urlpatterns = [
    # Misc
    re_path("^$", views.index, name="pybb_index"),
    re_path("^mark_as_read/", views.mark_as_read, name="mark_as_read"),
    re_path(
        "^category/(?P<category_id>\d+)/$", views.show_category, name="pybb_category"
    ),
    re_path(
        "^category/(?P<category_id>\d+)/mark_as_read/$",
        views.mark_as_read,
        name="mark_as_read",
    ),
    re_path("^forum/(?P<forum_id>\d+)/$", views.show_forum, name="pybb_forum"),
    re_path(
        "^forum/(?P<forum_id>\d+)/mark_as_read/$",
        views.mark_as_read,
        name="mark_as_read",
    ),
    # Feeds
    re_path("^feeds/topics/(?P<topic_id>\d+)/$", LastTopics(), name="pybb_feed_topics"),
    re_path("^feeds/posts/(?P<topic_id>\d+)/$", LastPosts(), name="pybb_feed_posts"),
    re_path("^feeds/topics/$", LastTopics(), name="pybb_feed_topics"),
    re_path("^feeds/posts/$", LastPosts(), name="pybb_feed_posts"),
    # Topic
    re_path("^topic/(?P<topic_id>\d+)/$", views.show_topic, name="pybb_topic"),
    re_path(
        "^forum/(?P<forum_id>\d+)/topic/add/$",
        views.add_post,
        {"topic_id": None},
        name="pybb_add_topic",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/stick/$", views.stick_topic, name="pybb_stick_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unstick/$",
        views.unstick_topic,
        name="pybb_unstick_topic",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/close/$", views.close_topic, name="pybb_close_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/open/$", views.open_topic, name="pybb_open_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unhide/$",
        views.toggle_hidden_topic,
        name="pybb_toggle_hid_topic",
    ),
    # Post
    re_path(
        "^topic/(?P<topic_id>\d+)/post/add/$",
        views.add_post,
        {"forum_id": None},
        name="pybb_add_post",
    ),
    re_path("^post/(?P<post_id>\d+)/$", views.show_post, name="pybb_post"),
    re_path("^post/(?P<post_id>\d+)/edit/$", views.edit_post, name="pybb_edit_post"),
    re_path(
        "^post/(?P<post_id>\d+)/delete/$", views.delete_post, name="pybb_delete_post"
    ),
    re_path(r"^latest_posts/$", views.all_latest, name="all_latest_posts"),
    re_path(
        r"^user_posts/(?P<this_user>[\w.@+-]+)/$",
        views.user_posts,
        name="all_user_posts",
    ),
    # Attachment
    re_path(
        "^attachment/(?P<hash>\w+)/$", views.show_attachment, name="pybb_attachment"
    ),
    # API
    re_path(
        "^api/post_ajax_preview/$",
        views.post_ajax_preview,
        name="pybb_post_ajax_preview",
    ),
    # Subscription
    re_path(
        "^topic/(?P<topic_id>\d+)/subscribe/$",
        views.add_subscription,
        name="pybb_add_subscription",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unsubscribe/$",
        views.delete_subscription,
        name="pybb_delete_subscription",
    ),
]

wlpoll/urls.py
#!/usr/bin/env python -tt
# encoding: utf-8
#

from .models import Poll
from django.urls import re_path
from . import views
from django.views.generic.dates import ArchiveIndexView

# delete this
info_dict = {"queryset": Poll.objects.all()}

urlpatterns = [
    re_path(
        r"^$",
        ArchiveIndexView.as_view(
            model=Poll, date_field="pub_date", template_name="wlpoll/poll_list.html"
        ),
        name="wlpoll_archive",
    ),
    re_path(r"^(?P<pk>[0-9]+)/$", views.DetailView.as_view(), name="wlpoll_detail"),
    re_path(r"(?P<object_id>\d+)/vote/$", views.vote, name="wlpoll_vote"),
]

wlpoll/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import datetime


def closed_date_default():
    return datetime.datetime.now() + datetime.timedelta(days=90)


class PollManager(models.Manager):
    def open(self):
        return self.all().exclude(closed_date__lte=datetime.datetime.now())


class Poll(models.Model):
    name = models.CharField(max_length=256)
    pub_date = models.DateTimeField("date published", default=datetime.datetime.now)
    closed_date = models.DateTimeField(
        "date closed", default=closed_date_default, blank=True, null=True
    )

    objects = PollManager()

    def total_votes(self):
        return self.choices.all().aggregate(models.Sum("votes"))["votes__sum"]

    def has_user_voted(self, u):
        return u.poll_votes.filter(poll=self).count() > 0

    def is_closed(self):
        if self.closed_date is None:
            return False
        return self.closed_date < datetime.datetime.now()

    def get_absolute_url(self):
        return reverse("wlpoll_detail", kwargs={"pk": self.id})

    def __str__(self):
        return self.name


class Choice(models.Model):
    poll = models.ForeignKey(Poll, related_name="choices", on_delete=models.CASCADE)
    choice = models.CharField(max_length=256)
    votes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return "%i:%s" % (self.votes, self.choice)


class Vote(models.Model):
    user = models.ForeignKey(User, related_name="poll_votes", on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)
    date_voted = models.DateTimeField("voted at", default=datetime.datetime.now)

wlpoll/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import (
    HttpResponseNotAllowed,
    HttpResponseRedirect,
    HttpResponseForbidden,
)
from django.urls import reverse
from .models import Poll, Choice, Vote
from django.views import generic


class DetailView(generic.DetailView):
    model = Poll
    template_name = "wlpoll/poll_detail.html"


# class ResultsView(generic.DetailView):
#    model = Poll
#    template_name = 'polls/results.html'


@login_required
def vote(request, object_id, next=None):
    if request.method == "GET":
        return HttpResponseNotAllowed(["POST"])

    p = get_object_or_404(Poll, pk=object_id)

    user = request.user
    if user.poll_votes.filter(poll=p):
        return HttpResponseForbidden("Can't vote more than once")

    if not p.is_closed() and "choice_id" in request.POST:
        c = get_object_or_404(Choice, pk=int(request.POST["choice_id"]), poll=p)

        c.votes += 1
        c.save()

        v = Vote.objects.create(user=user, poll=p, choice=c)
        v.save()

    return HttpResponseRedirect(reverse("wlpoll_detail", args=(p.id,)))

wlpoll/templates/wlpoll/base.html
{% extends "mainpage/base.html" %}
{% comment %}
   vim:ft=htmldjango
{% endcomment %}

{% load static %}

{% block extra_head %}
{{block.super}}
<link rel="stylesheet" type="text/css" media="all" href="{% static 'css/comments.css' %}" />
<script src="{% static 'js/highcharts_v5/highcharts.js' %}" type="text/javascript"></script>
{% endblock %}

{% block title %}Polls - {{ block.super }}{% endblock %}

wlpoll/templates/wlpoll/poll_detail.html
{% extends "wlpoll/base.html" %}
{% comment %}
    vim:ft=htmldjango
{% endcomment %}

{% load wlprofile_extras wlpoll_extras %}

{% load threadedcommentstags custom_date %}

{% block title %}{{ object.name }} - {{ block.super }}{% endblock %}

{% block content_header %}
    <h1>Poll: {{ object.name }}</h1>
{% endblock %}

{% block content_tabbing %}
{% if perms.wlpoll %}
<ul class="small tab-list">
    {% if perms.wlpoll.add_poll %}
    <li>
        <a href="/admin/wlpoll/poll/add/">Add New Poll</a>
    </li>
    {% endif %}
    {% if perms.wlpoll.change_poll %}
    <li>
        <a href="/admin/wlpoll/poll/{{object.id}}/">Edit</a>
    </li>
    {% endif %}
    {% if perms.wlpoll.delete_poll %}
    <li>
        <a href="/admin/wlpoll/poll/{{object.id}}/delete/">Delete</a>
    </li>
    {% endif %}
</ul>
{% endif %}

{% endblock %}

{% block content_section %}
<section class="blogEntry">
    <div id="chartContainer" style="width: 100%; height: 400px"></div>
    {% display_poll object %}
    <hr/>
    {% get_comment_count for object as ccount %}
    <span class="small posLeft"><a href="{{ object.get_absolute_url }}">{{ ccount }} comments, {{object.total_votes}} votes</a></span>
    <span class="small posRight">Posted on {{ object.pub_date|custom_date:user }}</span>
</section>

<section class="blogEntry">
    <h3>Comments on this Poll:</h3>
    {% include "threadedcomments/inlines/comments.html" %}
</section>
{% endblock %}

wlpoll/templates/wlpoll/poll_list.html
{% extends "mainpage/base.html" %}
{% comment %}
    vim:ft=htmldjango
{% endcomment %}

{% load static %}

{% block extra_head %}
{{ block.super}}
    <link rel="stylesheet" type="text/css" media="all" href="{% static 'css/wiki.css' %}"/>
{% endblock %}

{% load threadedcommentstags custom_date %}

{% block title %}Poll Archive - {{ block.super }}{% endblock %}

{% block content_header %}
    <h1>Poll Archive</h1>
{% endblock %}

{% block content_tabbing %}
{% if perms.wlpoll %}
<ul class="small tab-list">
    <li>
        {% if perms.wlpoll.add_poll %}
            <a href="/admin/wlpoll/poll/add/">Add New Poll</a>
        {% endif %}
    </li>
</ul>
{% endif %}
{% endblock %}

{% block content_section %}
<section class="blogEntry">
    <div class="post">
        <table>
            <tr>
                <th>Poll</th>
                <th>Begin</th>
                <th>End</th>
                <th>Votes</th>
                <th>Comments</th>
            </tr>

            {% for o in object_list %}
            {% get_comment_count for o as ccount %}
            <tr>
                <td><a href="{{o.get_absolute_url}}">{{ o.name }}</a></td>
                <td>{{ o.pub_date|custom_date:user }}</td>
                <td>{{ o.closed_date|custom_date:user }}</td>
                <td class="center">{{o.total_votes}}</td>
                <td class="right">{{ ccount }}</td>
            </tr>
            {% endfor %}
        </table>
    </div>
</section>
{% endblock %}