mainpage/urls.py
from django.urls import include, re_path
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django_registration.backends.activation.views import RegistrationView

from mainpage.forms import LoginTimezoneForm
from mainpage.forms import FormWithCaptcha

admin.autodiscover()

urlpatterns = [
    # Creating a sitemap.xml
    re_path(r"^sitemap\.xml", include("mainpage.sitemap_urls")),
    # Static view of robots.txt
    re_path(
        r"^robots\.txt",
        TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
    ),
    # Uncomment the next line to enable the admin:
    re_path(r"^admin/", admin.site.urls),
    # Django builtin / Registration
    # overwrite registration with own implementation
    re_path(
        r"^accounts/register/$",
        RegistrationView.as_view(form_class=FormWithCaptcha),
        name="django_registration_register",
    ),
    re_path(r"^accounts/", include("django_registration.backends.activation.urls")),
    re_path(
        r"^accounts/login/$", LoginView.as_view(authentication_form=LoginTimezoneForm)
    ),
    re_path(r"^accounts/", include("django.contrib.auth.urls")),
    re_path(r"^ratings/", include("star_ratings.urls", namespace="ratings")),
    # Formerly 3rd party
    re_path(r"^notification/", include("notification.urls")),
    re_path(r"^messages/", include("django_messages_wl.urls")),
    re_path(r"^threadedcomments/", include("threadedcomments.urls")),
    # Redirect old urls to new documentation
    re_path(
        r"^docs/wl/(?P<path>.*)",
        RedirectView.as_view(url="/documentation/%(path)s", permanent=True),
        name="docs_wl",
    ),
    re_path(
        r"^docs/$",
        RedirectView.as_view(url="/documentation/index.html", permanent=True),
        name="docs",
    ),
    # 3rd party, modified for widelands
    re_path(r"^wiki/", include("wiki.urls")),
    re_path(r"^news/", include("news.urls")),
    re_path(r"^forum/", include("pybb.urls")),
    # WL specific:
    re_path(r"^", include("mainpage.mainpage_urls")),
    re_path(
        r"^help/(?P<path>.*)",
        RedirectView.as_view(url="/encyclopedia/%(path)s", permanent=True),
    ),  # to not break old links
    re_path(r"^encyclopedia/", include("wlhelp.urls")),
    re_path(r"^webchat/", include("wlwebchat.urls")),
    re_path(r"^images/", include("wlimages.urls")),
    re_path(r"^profile/", include("wlprofile.urls")),
    re_path(r"^search/", include("wlsearch.urls")),
    re_path(r"^poll/", include("wlpoll.urls")),
    re_path(r"^maps/", include("wlmaps.urls")),
    re_path(r"^screenshots/", include("wlscreens.urls")),
    re_path(r"^ggz/", include("wlggz.urls")),
    re_path(r"^moderated/", include("check_input.urls")),
    re_path(r"^scheduling/", include("wlscheduling.urls")),
    re_path(r"^privacy/", include("privacy_policy.urls")),
    re_path(r"^addons/", include("wladdons_settings.urls")),
    # See: https://github.com/widelands/widelands-website/issues/376
    re_path(
        r"^feeds/news/",
        RedirectView.as_view(url="/news/feed", permanent=True),
    ),
]

try:
    from .local_urls import local_urlpatterns

    urlpatterns += local_urlpatterns
except ImportError:
    pass

handler500 = "mainpage.views.custom_http_500"

news/urls.py
from django.urls import re_path
from news.views import NewsList, YearNews, MonthNews, NewsDetail, CategoryView
from news.feeds import NewsPostsFeed


urlpatterns = [
    re_path(
        r"^(?P<year>[0-9]{4})/(?P<month>[-\w]+)/(?P<day>[0-9]+)/(?P<slug>[-\w]+)/$",
        NewsDetail.as_view(),
        name="news_detail",
    ),
    re_path(
        r"^(?P<year>\d{4})/(?P<month>[-\w]+)/$",
        MonthNews.as_view(),
        name="news_archive_month",
    ),
    re_path(r"^(?P<year>\d{4})/$", YearNews.as_view(), name="news_archive_year"),
    re_path(
        r"^category/(?P<slug>[-\w]+)/", CategoryView.as_view(), name="category_posts"
    ),
    re_path(
        r"^$", NewsList.as_view(template_name="news/post_list.html"), name="news_index"
    ),
    # Feed
    re_path(r"^feed/$", NewsPostsFeed()),
]

pybb/urls.py
from django.urls import re_path

from pybb import views
from pybb.feeds import LastPosts, LastTopics

urlpatterns = [
    # Misc
    re_path("^$", views.index, name="pybb_index"),
    re_path("^mark_as_read/", views.mark_as_read, name="mark_as_read"),
    re_path(
        "^category/(?P<category_id>\d+)/$", views.show_category, name="pybb_category"
    ),
    re_path(
        "^category/(?P<category_id>\d+)/mark_as_read/$",
        views.mark_as_read,
        name="mark_as_read",
    ),
    re_path("^forum/(?P<forum_id>\d+)/$", views.show_forum, name="pybb_forum"),
    re_path(
        "^forum/(?P<forum_id>\d+)/mark_as_read/$",
        views.mark_as_read,
        name="mark_as_read",
    ),
    # Feeds
    re_path("^feeds/topics/(?P<topic_id>\d+)/$", LastTopics(), name="pybb_feed_topics"),
    re_path("^feeds/posts/(?P<topic_id>\d+)/$", LastPosts(), name="pybb_feed_posts"),
    re_path("^feeds/topics/$", LastTopics(), name="pybb_feed_topics"),
    re_path("^feeds/posts/$", LastPosts(), name="pybb_feed_posts"),
    # Topic
    re_path("^topic/(?P<topic_id>\d+)/$", views.show_topic, name="pybb_topic"),
    re_path(
        "^forum/(?P<forum_id>\d+)/topic/add/$",
        views.add_post,
        {"topic_id": None},
        name="pybb_add_topic",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/stick/$", views.stick_topic, name="pybb_stick_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unstick/$",
        views.unstick_topic,
        name="pybb_unstick_topic",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/close/$", views.close_topic, name="pybb_close_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/open/$", views.open_topic, name="pybb_open_topic"
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unhide/$",
        views.toggle_hidden_topic,
        name="pybb_toggle_hid_topic",
    ),
    # Post
    re_path(
        "^topic/(?P<topic_id>\d+)/post/add/$",
        views.add_post,
        {"forum_id": None},
        name="pybb_add_post",
    ),
    re_path("^post/(?P<post_id>\d+)/$", views.show_post, name="pybb_post"),
    re_path("^post/(?P<post_id>\d+)/edit/$", views.edit_post, name="pybb_edit_post"),
    re_path(
        "^post/(?P<post_id>\d+)/delete/$", views.delete_post, name="pybb_delete_post"
    ),
    re_path(r"^latest_posts/$", views.all_latest, name="all_latest_posts"),
    re_path(
        r"^user_posts/(?P<this_user>[\w.@+-]+)/$",
        views.user_posts,
        name="all_user_posts",
    ),
    # Attachment
    re_path(
        "^attachment/(?P<hash>\w+)/$", views.show_attachment, name="pybb_attachment"
    ),
    # API
    re_path(
        "^api/post_ajax_preview/$",
        views.post_ajax_preview,
        name="pybb_post_ajax_preview",
    ),
    # Subscription
    re_path(
        "^topic/(?P<topic_id>\d+)/subscribe/$",
        views.add_subscription,
        name="pybb_add_subscription",
    ),
    re_path(
        "^topic/(?P<topic_id>\d+)/unsubscribe/$",
        views.delete_subscription,
        name="pybb_delete_subscription",
    ),
]

wlmaps/urls.py
#!/usr/bin/env python -tt
# encoding: utf-8
from django.urls import re_path
from .views import MapList, upload, view, edit_comment, download


urlpatterns = [
    re_path(r"^$", MapList.as_view(), name="wlmaps_index"),
    re_path(r"^upload/$", upload, name="wlmaps_upload"),
    re_path(r"^(?P<map_slug>[-\w]+)/$", view, name="wlmaps_view"),
    re_path(
        r"^(?P<map_slug>[-\w]+)/edit_comment/$",
        edit_comment,
        name="wlmaps_edit_comment",
    ),
    re_path(r"^(?P<map_slug>[-\w]+)/download/$", download, name="wlmaps_download"),
]

wlmaps/models.py
#!/usr/bin/env python -tt
# encoding: utf-8

from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.contenttypes.fields import GenericRelation
from star_ratings.models import Rating

import datetime


try:
    from notification import models as notification
except ImportError:
    notification = None


class Map(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)
    author = models.CharField(max_length=255)
    w = models.PositiveIntegerField(verbose_name="Width")
    h = models.PositiveIntegerField(verbose_name="Height")
    nr_players = models.PositiveIntegerField(verbose_name="Max Players")

    descr = models.TextField(verbose_name="Description")
    hint = models.TextField(verbose_name="Hint", blank=True)
    minimap = models.ImageField(verbose_name="Minimap", upload_to="wlmaps/minimaps")
    file = models.FileField(verbose_name="Mapfile", upload_to="wlmaps/maps")

    world_name = models.CharField(max_length=50, blank=True)

    pub_date = models.DateTimeField(default=datetime.datetime.now)
    uploader_comment = models.TextField(verbose_name="Uploader comment", blank=True)
    uploader = models.ForeignKey(User, on_delete=models.CASCADE)
    nr_downloads = models.PositiveIntegerField(verbose_name="Download count", default=0)
    wl_version_after = models.CharField(
        # The field is called 'wl_version_after' even though it actually means the
        # _minimum_ WL version required to play the map for historical reasons.
        verbose_name="Minimum WL version",
        max_length=10,
        null=True,
        blank=True,
    )
    ratings = GenericRelation(Rating)

    class Meta:
        ordering = ("-pub_date",)
        get_latest_by = "pub_date"

    def get_absolute_url(self):
        return reverse("wlmaps_view", kwargs={"map_slug": self.slug})

    def __str__(self):
        return "%s by %s" % (self.name, self.author)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)

        # Check if this is a new map for sending notifications
        is_new = False
        try:
            Map.objects.get(slug=self.slug)
        except Map.DoesNotExist:
            is_new = True

        map = super(Map, self).save(*args, **kwargs)

        # Send notifications only on new maps, not when updating fields, e.g.
        # nr_downloads
        if notification and is_new:
            notification.send(
                notification.get_observers_for("maps_new_map", excl_user=self.uploader),
                "maps_new_map",
                {
                    "mapname": self.name,
                    "url": self.get_absolute_url(),
                    "user": self.uploader,
                    "uploader_comment": self.uploader_comment,
                },
            )

        return map

    def delete(self, *args, **kwargs):
        """Delete also corresponding map files."""

        # For some reason this throws no error if a file didn't exist
        self.minimap.delete()
        self.file.delete()
        super(Map, self).delete(*args, **kwargs)

wlmaps/views.py
#!/usr/bin/env python -tt
# encoding: utf-8
#
import os

from .forms import UploadMapForm, EditCommentForm
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import (
    HttpResponseRedirect,
    HttpResponse,
    JsonResponse,
    HttpResponseBadRequest,
)

from django.conf import settings
from . import filters, models
from mainpage.wl_utils import get_pagination, is_ajax


#########
# Views #
#########
class MapList(ListView):
    model = models.Map

    @property
    def filter(self):
        if not hasattr(self, "_filter"):
            get = self.request.GET.copy()
            if not get.get("o"):
                get["o"] = "-pub_date"

            self._filter = filters.MapFilter(get, queryset=super().get_queryset())

        return self._filter

    def get_queryset(self):
        return self.filter.qs

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx.update(
            {
                "filter": self.filter,
            }
        )
        ctx.update(
            get_pagination(self.request, ctx["object_list"], settings.MAPS_PER_PAGE)
        )
        return ctx

    def options(self, request, *args, **kwargs):
        if is_ajax(request):
            q = request.GET.get("q", "")
            f = request.GET.get("f", "")

            if f == "uploader":
                values = (
                    User.objects.exclude(is_active=False)
                    .filter(username__icontains=q)
                    .values_list("username")
                )
            elif f == "author":
                # convert to set and back to list because distinct is not supported with sqlite
                values = list(
                    set(
                        models.Map.objects.filter(author__icontains=q)
                        .order_by("author")
                        .values_list("author", flat=True)
                    )
                )
            else:
                return HttpResponseBadRequest()

            return JsonResponse(list(map(lambda x: {"value": x}, values)), safe=False)
        else:
            return HttpResponseBadRequest()


def download(request, map_slug):
    """Very simple view that just returns the binary data of this map and
    increases the download count."""
    m = get_object_or_404(models.Map, slug=map_slug)

    file = open(m.file.path, "rb")
    data = file.read()
    filename = os.path.basename("%s.wmf" % m.name)

    # Remember that this has been downloaded
    m.nr_downloads += 1
    m.save(update_fields=["nr_downloads"])

    response = HttpResponse(data, content_type="application/octet-stream")
    response["Content-Disposition"] = 'attachment; filename="%s"' % filename

    return response


def view(request, map_slug):
    map = get_object_or_404(models.Map, slug=map_slug)
    context = {
        "map": map,
    }
    return render(request, "wlmaps/map_detail.html", context)


@login_required
def edit_comment(request, map_slug):
    map = get_object_or_404(models.Map, slug=map_slug)
    if request.method == "POST":
        form = EditCommentForm(request.POST)
        if form.is_valid():
            map.uploader_comment = form.cleaned_data["uploader_comment"]
            map.save(update_fields=["uploader_comment"])
            return HttpResponseRedirect(map.get_absolute_url())
    else:
        form = EditCommentForm(instance=map)

    context = {"form": form, "map": map}

    return render(request, "wlmaps/edit_comment.html", context)


@login_required
def upload(request):
    if request.method == "POST":
        form = UploadMapForm(request.POST, request.FILES)
        if form.is_valid():
            map = form.save(commit=False)
            map.uploader = request.user
            map.save()
            return HttpResponseRedirect(map.get_absolute_url())
    else:
        form = UploadMapForm()

    context = {
        "form": form,
    }
    return render(request, "wlmaps/upload.html", context)

wlmaps/templates/wlmaps/base.html
{% extends "mainpage/base.html" %}
{% load static %}
{% comment %}
   vim:ft=htmldjango
{% endcomment %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" media="all" href="{% static 'css/forum.css' %}" />
<link rel="stylesheet" type="text/css" media="all" href="{% static 'css/maps.css' %}" />
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}" />
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
{{block.super}}
{% endblock %}

{% block title %}Maps - {{ block.super }}{% endblock %}

wlmaps/templates/wlmaps/edit_comment.html
{% extends "wlmaps/base.html" %}
{% load static %}

{% block content_header %}
    <h1>Edit comment: {{ map.name }}</h1>
{% endblock %}
{% block content_section %}
<section class="blogEntry">
    <form enctype="multipart/form-data"
          action="{% url 'wlmaps_edit_comment' map.slug %}" method="post">
        <div>
            {{ form.uploader_comment.label_tag }}
            <span class="posRight">
				<a href="/wiki/WikiSyntax" title="Opens new Tab/Window" target="_blank">
					<img src="{% static 'img/menu_help.png' %}" alt="Help on Syntax"
                         class="middle">
					Help on Syntax
				</a>
			</span>
            {{ form.uploader_comment }}
        </div>
        {% if form.uploader_comment.errors %}
            <span class="errormessage">{{ form.uploader_comment.errors }}</span><br/>
        {% endif %}
        {% csrf_token %}
        <button type="submit">
            <img src="{% static 'forum/img/send.png' %}" alt="Submit" class="middle"/>
            <span class="middle">Submit</span>
        </button>
    </form>
</section>
{% endblock %}

wlmaps/templates/wlmaps/map_detail.html
{% extends "wlmaps/base.html" %}
{% comment %}
    vim:ft=htmldjango
{% endcomment %}

{% load custom_date %}
{% load wlprofile_extras %}
{% load threadedcommentstags %}
{% load wl_markdown %}
{% load ratings %}
{% load static %}

{% block title %}{{ map.name }} - {{ block.super }}{% endblock %}

{% block extra_head %}
{{ block.super }}
<link rel="stylesheet" type="text/css" media="all"
      href="{% static 'css/comments.css' %}"/>
{% endblock %}

{% block content_header %}
    <h1>Map: {{ map.name }}</h1>
{% endblock %}

{% block content_section %}
<section class="blogEntry">
    <div>
        <a href="{% url 'wlmaps_index' %}">Maps</a> &#187; {{ map.name }}
    </div>
    <img class="posLeft map" src="{{ MEDIA_URL }}{{ map.minimap }}"
         alt="{{ map.name }}"/>
    <div>
        <h3>Description:</h3>
        <p>{{ map.descr|wl_markdown:"bleachit" }}</p>
    </div>
    {% if map.hint %}
    <div style="clear: left;">
        <h3>Hint:</h3>
        <p>{{ map.hint|wl_markdown:"bleachit" }}</p>
    </div>
    {% endif %}

    <div style="clear: left;">
        <h3>Comment by uploader:</h3>
        <div>{{ map.uploader_comment|wl_markdown:"bleachit" }}</div>
        {% if user == map.uploader %}
        <a class="button posLeft" href="{% url 'wlmaps_edit_comment' map.slug %}">
            <img alt="Edit" title="Edit your comment" class="middle"
                 src="{% static 'forum/img/edit.png' %}">
            <span class="middle">Edit</span>
        </a>
        {% endif %}
    </div>
    <br/>

    <div>
        <h3>Basic Information:</h3>
        <table>
            <tr>
                <td class="grey">Author:</td>
                <td>{{ map.author }}</td>
            </tr>
            <tr>
                <td class="grey">World:</td>
                <td>
                    {% if map.world_name %}
                        {{ map.world_name|title }}
                    {% else %}
                        One World
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td class="grey">Dimensions:</td>
                <td>{{ map.w }} x {{ map.h }}</td>
            </tr>
            <tr>
                <td class="grey">Max. Players:</td>
                <td>{{ map.nr_players }}</td>
            </tr>
            <tr>
                <td class="grey">Downloads:</td>
                <td>{{ map.nr_downloads }}</td>
            </tr>
            <tr>
                {% get_comment_count for map as ccount %}
                <td class="grey">Comments:</td>
                <td>{{ ccount }}</td>
            </tr>
            <tr>
                <td class="grey">Rating:</td>
                <td>
                    {% ratings map template_name='star_rating/rate.html' %}
                </td>
            </tr>
            <tr>
                <td class="grey">Upload:</td>
                <td>by {{ map.uploader|user_link }} at {{ map.pub_date|custom_date:user }}
                </td>
            </tr>
        </table>

        {% if not map.world_name %}
        <div>
            {% include 'wlmaps/inlines/version_info.html'%}
        </div>
        {% endif %}
    </div>

    <div style="margin: 1em 0px 1em 0px">
        <a class="button posLeft" href="{% url 'wlmaps_download' map.slug %}">
            <img src="{% static 'img/arrow_down_short.png' %}" alt="" class="middle"/>
            <span class="middle">Download this map</span>
        </a>
    </div>
</section>

<section class="blogEntry">
    <h3>Comments on this Map:</h3>
    {% with map as object %}
    {% include "threadedcomments/inlines/comments.html" %}
    {% endwith %}
</section>
{% endblock %}

wlmaps/templates/wlmaps/map_list.html
{% extends "wlmaps/base.html" %}
{% comment %}
    vim:ft=htmldjango
{% endcomment %}

{% load custom_date %}
{% load wlprofile_extras %}
{% load threadedcommentstags %}
{% load wl_extras %}
{% load ratings %}
{% load static %}

{% block content_header %}
    <h1>Maps</h1>
{% endblock %}
{% block content_tabbing %}
<ul class="tab-list small">
    <li>
        <a href="{% url 'wlmaps_upload' %}">Upload a new map</a>
    </li>
</ul>
{% endblock %}

{% block extra_head %}
<link rel="stylesheet" type="text/css" media="all"
      href="{% static 'css/messages.css' %}"/>
<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
<script>
    $(function() {
        $( "#id_author__iexact" ).autocomplete({
            source: function (request, response) {
                $.ajax('?' + $.param({f: 'author', 'q': request.term}), {
                    dataType: 'json',
                    method: 'OPTIONS',
                }).done(function (r) { response(r)})
            },
            minLength: 3,
        });
        $( "#id_uploader" ).autocomplete({
            source: function (request, response) {
                $.ajax('?' + $.param({f: 'uploader', 'q': request.term}), {
                    dataType: 'json',
                    method: 'OPTIONS',
                }).done(function (r) { response(r)})
            },
            minLength: 3,
        });
    });
</script>
{{ block.super}}
{% endblock %}

{% block content_section %}

<section class="blogEntry">
    <p>
        <span class="errormessage">Please note:</span> Uploading maps on the website
        which use terrains
        from add-ons will not work! Starting with Widelands version 1.0 it is
        recommended to upload new
        maps within the game as an add-on. To do so start the "Add-Ons Packager" via
        "Main menu → Add-Ons → Tab Development → Launch the add-ons packager".
    </p>
    <p>
        The map files have to be placed in the Widelands map directory to be found by
        the game. Check the <a
            href="/wiki/Technical%20FAQ/#where-are-my-maps-and-savegames-stored">Technical
        FAQ</a> to find the map directory.
    </p>

    <form method="get">
        {{ form.non_field_errors }}
        <table class="maps-filter">
            <tr>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.name__icontains %}
                <td class="spacer"></td>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.nr_players %}
            </tr>
            <tr>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.author__iexact %}
                <td class="spacer"></td>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.uploader %}
            </tr>
            <tr>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.w %}
                <td class="spacer"></td>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.h %}
            </tr>
            <tr>
                {% include 'wlmaps/inlines/form_field_td.html' with field=filter.form.o %}
                <td class="spacer" colspan="2"></td>
                <td colspan="1" class="right"><input type="submit"
                                                     value="Apply filters"/></td>
            </tr>
        </table>
    </form>
    {% include "pagination/pagination.html" %}
    <br/>
    <table class="maps">
        {% for map in page_obj %}
        <tr class="{% cycle 'odd' 'even' %}">
            <td class="first-column"><a href="{{ map.get_absolute_url }}"><img
                    class="minimap" src="{{ MEDIA_URL }}{{ map.minimap }}"
                    alt="{{ map.name }}"/></a></td>
            <td>
                <h3><a class="invertedColor" href="{{ map.get_absolute_url }}">{{ map.name }}</a></h3>
                <table>
                    <tr>
                        <td class="grey">Author:</td>
                        <td>{{ map.author }}</td>
                        <td class="spacer"></td>
                        <td class="grey">Dimensions:</td>
                        <td>{{ map.w }} x {{ map.h }}</td>
                    </tr>
                    <tr>
                        <td class="grey">World:</td>
                        <td>
                            {% if map.world_name %}
                                {{ map.world_name|title }}
                            {% else %}
                                One World
                            {% endif %}
                        </td>
                        <td class="spacer"></td>
                        <td class="grey">Max. Players:</td>
                        <td>{{ map.nr_players }}</td>
                    </tr>
                    <tr>
                        <td class="grey">Rating:</td>
                        <td>
                            {% ratings map template_name='star_rating/average.html' %}
                        </td>
                        <td class="spacer"></td>
                        {% get_comment_count for map as ccount %}
                        <td class="grey">Comments:</td>
                        <td>{{ ccount }}</td>
                    </tr>
                    <tr>
                        <td class="grey">Upload:</td>
                        <td colspan="4">by {{ map.uploader|user_link }} at {{ map.pub_date|custom_date:user }}
                        </td>
                    </tr>
                    {% if not map.world_name %}
                    <tr>
                        <td colspan="5">
                            {% include 'wlmaps/inlines/version_info.html' %}
                        </td>
                    </tr>
                    {% endif %}
                    <tr>
                        <td class="grey">Downloads:</td>
                        <td>{{ map.nr_downloads }}</td>
                        <td class="spacer"></td>
                        <td colspan="2">
                            <a class="button"
                               href="{% url 'wlmaps_download' map.slug %}">
                                <img src="{% static 'img/arrow_down_short.png' %}"
                                     alt="" class="middle"/>
                                <span class="middle">Direct Download</span>
                            </a>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        {% endfor %}
    </table>
    <br/>
    {% include "pagination/pagination.html" %}
</section>
{% endblock %}

wlmaps/templates/wlmaps/upload.html
{% extends "wlmaps/base.html" %}
{% comment %}
    vim:ft=htmldjango
{% endcomment %}

{% load static %}

{% block title %}Upload - {{ block.super }}{% endblock %}

{% block content_header %}
    <h1>Map Upload</h1>
{% endblock %}

{% block content_section %}
<section class="blogEntry">
    <div class="breadCrumb">
        <a href="{% url 'wlmaps_index' %}">Maps</a> &#187; Upload
    </div>
    <p>
        <span class="errormessage">Please note:</span> Uploading maps on the website
        which use terrains
        from add-ons will not work! Starting with Widelands version 1.0 it is
        recommended to upload new
        maps within the game as an add-on. To do so start the "Add-Ons Packager" via
        "Main menu → Add-Ons → Tab Development → Launch the add-ons packager".
    </p>
    <form enctype="multipart/form-data" action="{% url 'wlmaps_upload' %}"
          method="post">
        {{ form.file.label_tag }} {{ form.file }}<br/>
        {% if form.file.errors %}
            <span class="errormessage">{{ form.file.errors }}</span><br/>
        {% endif %}
        <div>
            {{ form.uploader_comment.label_tag }}
            <span class="posRight">
				<a href="/wiki/WikiSyntax" title="Opens new Tab/Window" target="_blank">
					<img src="{% static 'img/menu_help.png' %}" alt="Help on Syntax"
                         class="middle">
					Help on Syntax
				</a>
			</span>
            {{ form.uploader_comment }}
        </div>
        {% if form.uploader_comment.errors %}
            <span class="errormessage">{{ form.uploader_comment.errors }}</span><br/>
        {% endif %}
        {% csrf_token %}
        <br/>
        <input type="submit" value="Upload"/>
    </form>
</section>
{% endblock %}